import { Flex, HStack, Grid, Image, Text } from "@chakra-ui/react";
import { CheckCircleIcon } from '@chakra-ui/icons'


export default function TravelTypes(){
    return (
        <>
            <HStack
                h={145}
                w={1160}
                justify="space-between"
                display={['none', 'none', 'flex', 'flex']}
            >
                <Flex
                    flexDir="column"
                    align="top"
                    justify="top"
                    h="100%"
                >
                    <Image
                        src="/images/Nightlife.svg"
                        alt="vida noturna"
                        w={85}
                    />
                    <Text
                        fontWeight="semibold"
                        color="heading_text_dark"
                        justifyContent="center"
                        align="center"
                    >
                        vida noturna
                    </Text>
                </Flex>
                <Flex
                    flexDir="column"
                    align="top"
                    justify="top"
                    h="100%"
                >
                    <Image
                        src="/images/surf_1.svg"
                        alt="praia"
                        w="80px"
                    />
                    <Text
                        fontWeight="semibold"
                        color="heading_text_dark"
                        justifyContent="center"
                        align="center"
                    >
                        praia
                    </Text>
                </Flex>
                <Flex
                    flexDir="column"
                    align="top"
                    justify="top"
                    h="100%"
                >
                    <Image
                        src="/images/building_1.svg"
                        alt="moderno"
                        w="80px"
                    />
                    <Text
                        fontWeight="semibold"
                        color="heading_text_dark"
                        justifyContent="center"
                        align="center"
                    >
                        moderno
                    </Text>
                </Flex>
                <Flex
                    flexDir="column"
                    align="top"
                    justify="top"
                    h="100%"
                >
                    <Image
                        src="/images/museum_1.svg"
                        alt="classico"
                        w="80px"
                    />
                    <Text
                        fontWeight="semibold"
                        color="heading_text_dark"
                        justifyContent="center"
                        align="center"
                    >
                        classico
                    </Text>
                </Flex>
                <Flex
                    flexDir="column"
                    align="top"
                    justify="top"
                    h="100%"
                >
                    <Image
                        src="/images/earth_1.svg"
                        alt="e mais..."
                        w="80px"
                    />
                    <Text
                        fontWeight="semibold"
                        color="heading_text_dark"
                        justifyContent="center"
                        align="center"
                    >
                        e mais...
                    </Text>
                </Flex>
            </HStack>
            <Grid
                templateColumns='repeat(2, 1fr)' gap={1}
                display={['grid', 'grid', 'none', 'none']}
            >
                <Flex
                    align="center"
                    justify="center"
                    h="100%"
                    mt={3}
                    w="100%"
                >
                    <CheckCircleIcon
                        w={20}
                        color="highlight"
                    />
                    <Text
                        fontWeight="medium"
                        color="heading_text_dark"
                        justifyContent="center"
                        align="center"
                        fontSize={18}
                    >
                        vida noturna
                    </Text>
                </Flex>
                <Flex
                    align="center"
                    justify="center"
                    h="100%"
                    mt={3}
                    w="100%"
                >
                    <CheckCircleIcon
                        w={20}
                        color="highlight"
                    />
                    <Text
                        fontWeight="medium"
                        color="heading_text_dark"
                        justifyContent="center"
                        align="center"
                        fontSize={18}
                    >
                        praia
                    </Text>
                </Flex>
                <Flex
                    align="center"
                    justify="center"
                    h="100%"
                    mt={3}
                    w="100%"
                >
                    <CheckCircleIcon
                        w={20}
                        color="highlight"
                    />
                    <Text
                        fontWeight="medium"
                        color="heading_text_dark"
                        justifyContent="center"
                        align="center"
                        fontSize={18}
                    >
                        moderno
                    </Text>
                </Flex>
                <Flex
                    align="center"
                    justify="center"
                    h="100%"
                    mt={3}
                    w="100%"
                >
                    <CheckCircleIcon
                        w={20}
                        color="highlight"
                    />
                    <Text
                        fontWeight="medium"
                        color="heading_text_dark"
                        justifyContent="center"
                        align="center"
                        fontSize={18}
                    >
                        classico
                    </Text>
                </Flex>
                <Flex
                    align="center"
                    justify="center"
                    h="100%"
                    mt={3}
                    w="100%"
                >
                    <CheckCircleIcon
                        w={20}
                        color="highlight"
                    />
                    <Text
                        fontWeight="medium"
                        color="heading_text_dark"
                        justifyContent="center"
                        align="center"
                        fontSize={18}
                    >
                        e mais...
                    </Text>
                </Flex>
            </Grid>
        </>
    )
}